package com.wujia.pet.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.persistence.CascadeType;
import jakarta.persistence.OneToMany;
import jakarta.validation.constraints.NotBlank;
import java.util.Arrays;
import java.util.List;
import java.util.ArrayList;

@Entity
@Table(indexes = {
        @Index(name = "idx_place_source", columnList = "source_provider,source_poi_id"),
        @Index(name = "idx_place_name_address", columnList = "name,address")
})
public class PetFriendlyPlace {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank
    @Column(nullable = false, length = 120)
    private String name;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private PlaceType type = PlaceType.PARK;

    @Column(length = 240)
    private String address;

    @Column(length = 120)
    private String phone;

    private Double latitude;

    private Double longitude;

    @Column(length = 500)
    private String description;

    @Column(length = 800)
    private String tags;

    private boolean indoorAllowed;

    private boolean largeDogFriendly;

    private boolean catFriendly;

    private boolean leashRequired;

    private boolean waterAvailable;

    private boolean parkingAvailable;

    private boolean feeRequired;

    @Column(length = 500)
    private String policyNote;

    @Column(name = "source_provider", length = 32)
    private String sourceProvider;

    @Column(name = "source_poi_id", length = 80)
    private String sourcePoiId;

    @Column(name = "source_keyword", length = 120)
    private String sourceKeyword;

    @Column(name = "crawl_batch_id", length = 64)
    private String crawlBatchId;

    @Column(name = "auto_generated")
    private Boolean autoGenerated = false;

    @Enumerated(EnumType.STRING)
    @Column(name = "place_source_type", nullable = false, length = 20, columnDefinition = "varchar(20) not null default 'USER_UPLOAD'")
    private PlaceSourceType placeSourceType = PlaceSourceType.USER_UPLOAD;

    @Column(name = "last_crawled_at")
    private java.time.LocalDateTime lastCrawledAt;

    @Column(name = "city_code", length = 30)
    private String cityCode = "";

    @ManyToOne(optional = false)
    private UserAccount uploadedBy;

    @OneToMany(mappedBy = "place", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<WalkGroup> walkGroups = new ArrayList<>();

    @Transient
    private double averageRating;

    @Transient
    private long commentCount;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public PlaceType getType() {
        return type;
    }

    public void setType(PlaceType type) {
        this.type = type;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone == null ? "" : phone.trim();
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public List<String> getTagList() {
        if (tags == null || tags.isBlank()) {
            return List.of();
        }
        return Arrays.stream(tags.split(","))
                .map(String::trim)
                .filter(tag -> !tag.isBlank())
                .distinct()
                .toList();
    }

    public boolean isIndoorAllowed() {
        return indoorAllowed;
    }

    public void setIndoorAllowed(boolean indoorAllowed) {
        this.indoorAllowed = indoorAllowed;
    }

    public boolean isLargeDogFriendly() {
        return largeDogFriendly;
    }

    public void setLargeDogFriendly(boolean largeDogFriendly) {
        this.largeDogFriendly = largeDogFriendly;
    }

    public boolean isCatFriendly() {
        return catFriendly;
    }

    public void setCatFriendly(boolean catFriendly) {
        this.catFriendly = catFriendly;
    }

    public boolean isLeashRequired() {
        return leashRequired;
    }

    public void setLeashRequired(boolean leashRequired) {
        this.leashRequired = leashRequired;
    }

    public boolean isWaterAvailable() {
        return waterAvailable;
    }

    public void setWaterAvailable(boolean waterAvailable) {
        this.waterAvailable = waterAvailable;
    }

    public boolean isParkingAvailable() {
        return parkingAvailable;
    }

    public void setParkingAvailable(boolean parkingAvailable) {
        this.parkingAvailable = parkingAvailable;
    }

    public boolean isFeeRequired() {
        return feeRequired;
    }

    public void setFeeRequired(boolean feeRequired) {
        this.feeRequired = feeRequired;
    }

    public String getPolicyNote() {
        return policyNote;
    }

    public void setPolicyNote(String policyNote) {
        this.policyNote = policyNote;
    }

    public String getSourceProvider() {
        return sourceProvider;
    }

    public void setSourceProvider(String sourceProvider) {
        this.sourceProvider = sourceProvider;
    }

    public String getSourcePoiId() {
        return sourcePoiId;
    }

    public void setSourcePoiId(String sourcePoiId) {
        this.sourcePoiId = sourcePoiId;
    }

    public String getSourceKeyword() {
        return sourceKeyword;
    }

    public void setSourceKeyword(String sourceKeyword) {
        this.sourceKeyword = sourceKeyword;
    }

    public String getCrawlBatchId() {
        return crawlBatchId;
    }

    public void setCrawlBatchId(String crawlBatchId) {
        this.crawlBatchId = crawlBatchId;
    }

    public boolean isAutoGenerated() {
        return Boolean.TRUE.equals(autoGenerated);
    }

    public void setAutoGenerated(Boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public PlaceSourceType getPlaceSourceType() {
        return placeSourceType == null ? PlaceSourceType.USER_UPLOAD : placeSourceType;
    }

    public void setPlaceSourceType(PlaceSourceType placeSourceType) {
        this.placeSourceType = placeSourceType == null ? PlaceSourceType.USER_UPLOAD : placeSourceType;
    }

    public boolean isImportedPlace() {
        return PlaceSourceType.IMPORTED.equals(getPlaceSourceType());
    }

    public boolean isUserUploadPlace() {
        return PlaceSourceType.USER_UPLOAD.equals(getPlaceSourceType());
    }

    public java.time.LocalDateTime getLastCrawledAt() {
        return lastCrawledAt;
    }

    public void setLastCrawledAt(java.time.LocalDateTime lastCrawledAt) {
        this.lastCrawledAt = lastCrawledAt;
    }

    public String getCityCode() {
        return cityCode;
    }

    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? "" : cityCode.trim();
    }

    public UserAccount getUploadedBy() {
        return uploadedBy;
    }

    public void setUploadedBy(UserAccount uploadedBy) {
        this.uploadedBy = uploadedBy;
    }

    public double getAverageRating() {
        return averageRating;
    }

    public void setAverageRating(double averageRating) {
        this.averageRating = averageRating;
    }

    public long getCommentCount() {
        return commentCount;
    }

    public void setCommentCount(long commentCount) {
        this.commentCount = commentCount;
    }

    public String getRatingText() {
        return commentCount == 0 ? "暂无评分" : String.format("%.1f", averageRating);
    }
}
